/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Eduardo
 */
public class MainFrame extends javax.swing.JFrame {

    private int decimalValue, gate;
    private boolean mode, controlBy;        

    /**
     * Creates new form tela
     */
    public MainFrame() {
        initComponents();
        controlBy = false; // False = Software | True = Hardware
        jCheckBoxSoftware.setSelected(true);
        jCheckBoxHardware.setSelected(false);
        mode = true; // False = GatesMode | True = BinMode
        binMode.setSelected(true);
        gatesMode.setSelected(false);
        jComboBoxGatesMenu.setEnabled(false);
        jToggleButtonInput1.setEnabled(false);
        jToggleButtonInput2.setEnabled(false);
        //jButtonSync.setIcon(new ImageIcon(("sync.jpg")));            
        decimalValue = gate = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxGatesMenu = new javax.swing.JComboBox();
        jSliderDSW3 = new javax.swing.JSlider();
        jSliderDSW2 = new javax.swing.JSlider();
        jSliderDSW1 = new javax.swing.JSlider();
        jPanelLed7 = new javax.swing.JPanel();
        jPanelLed6 = new javax.swing.JPanel();
        jPanelLed5 = new javax.swing.JPanel();
        jPanelLed4 = new javax.swing.JPanel();
        jPanelLed3 = new javax.swing.JPanel();
        jPanelLed2 = new javax.swing.JPanel();
        jPanelLed1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        binMode = new javax.swing.JRadioButton();
        gatesMode = new javax.swing.JRadioButton();
        jPanelConnection = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jCheckBoxSoftware = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jCheckBoxHardware = new javax.swing.JCheckBox();
        jButtonConnect = new javax.swing.JButton();
        jButtonDisconnect = new javax.swing.JButton();
        jToggleButtonInput1 = new javax.swing.JToggleButton();
        jToggleButtonInput2 = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemRestart = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuContolMode = new javax.swing.JMenu();
        jRadioButtonMenuItemSoftware = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemHardware = new javax.swing.JRadioButtonMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuConnection = new javax.swing.JMenu();
        jRadioButtonMenuItemConnected = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemDisconnected = new javax.swing.JRadioButtonMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemUpdate = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISDEM");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(415, 460));
        setMinimumSize(new java.awt.Dimension(415, 460));
        setPreferredSize(new java.awt.Dimension(415, 460));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxGatesMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NOT (NÃO)", "AND (E)", "OR (OU)", "NOR", "NAND", "XOR", "XNOR" }));
        getContentPane().add(jComboBoxGatesMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 130, 40));

        jSliderDSW3.setMaximum(1);
        jSliderDSW3.setOrientation(javax.swing.JSlider.VERTICAL);
        jSliderDSW3.setValue(0);
        jSliderDSW3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderDSW3MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jSliderDSW3MouseMoved(evt);
            }
        });
        jSliderDSW3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSliderDSW3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jSliderDSW3MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jSliderDSW3MousePressed(evt);
            }
        });
        getContentPane().add(jSliderDSW3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 30, 50));

        jSliderDSW2.setMaximum(1);
        jSliderDSW2.setOrientation(javax.swing.JSlider.VERTICAL);
        jSliderDSW2.setToolTipText("");
        jSliderDSW2.setValue(0);
        jSliderDSW2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderDSW2MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jSliderDSW2MouseMoved(evt);
            }
        });
        jSliderDSW2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSliderDSW2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jSliderDSW2MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jSliderDSW2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderDSW2MouseReleased(evt);
            }
        });
        getContentPane().add(jSliderDSW2, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 150, 30, 50));

        jSliderDSW1.setMaximum(1);
        jSliderDSW1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSliderDSW1.setValue(0);
        jSliderDSW1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderDSW1MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jSliderDSW1MouseMoved(evt);
            }
        });
        jSliderDSW1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSliderDSW1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jSliderDSW1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jSliderDSW1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderDSW1MouseReleased(evt);
            }
        });
        getContentPane().add(jSliderDSW1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 40, 50));

        jPanelLed7.setBackground(java.awt.Color.gray);
        jPanelLed7.setToolTipText("");
        jPanelLed7.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jPanelLed7Layout = new javax.swing.GroupLayout(jPanelLed7);
        jPanelLed7.setLayout(jPanelLed7Layout);
        jPanelLed7Layout.setHorizontalGroup(
            jPanelLed7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelLed7Layout.setVerticalGroup(
            jPanelLed7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelLed7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jPanelLed6.setBackground(java.awt.Color.gray);
        jPanelLed6.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jPanelLed6Layout = new javax.swing.GroupLayout(jPanelLed6);
        jPanelLed6.setLayout(jPanelLed6Layout);
        jPanelLed6Layout.setHorizontalGroup(
            jPanelLed6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelLed6Layout.setVerticalGroup(
            jPanelLed6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelLed6, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 60, -1, -1));

        jPanelLed5.setBackground(java.awt.Color.gray);
        jPanelLed5.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jPanelLed5Layout = new javax.swing.GroupLayout(jPanelLed5);
        jPanelLed5.setLayout(jPanelLed5Layout);
        jPanelLed5Layout.setHorizontalGroup(
            jPanelLed5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelLed5Layout.setVerticalGroup(
            jPanelLed5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelLed5, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 60, -1, 30));

        jPanelLed4.setBackground(java.awt.Color.gray);
        jPanelLed4.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jPanelLed4Layout = new javax.swing.GroupLayout(jPanelLed4);
        jPanelLed4.setLayout(jPanelLed4Layout);
        jPanelLed4Layout.setHorizontalGroup(
            jPanelLed4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelLed4Layout.setVerticalGroup(
            jPanelLed4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelLed4, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 60, -1, -1));

        jPanelLed3.setBackground(java.awt.Color.gray);
        jPanelLed3.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jPanelLed3Layout = new javax.swing.GroupLayout(jPanelLed3);
        jPanelLed3.setLayout(jPanelLed3Layout);
        jPanelLed3Layout.setHorizontalGroup(
            jPanelLed3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelLed3Layout.setVerticalGroup(
            jPanelLed3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelLed3, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 60, -1, -1));

        jPanelLed2.setBackground(java.awt.Color.gray);
        jPanelLed2.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jPanelLed2Layout = new javax.swing.GroupLayout(jPanelLed2);
        jPanelLed2.setLayout(jPanelLed2Layout);
        jPanelLed2Layout.setHorizontalGroup(
            jPanelLed2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelLed2Layout.setVerticalGroup(
            jPanelLed2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelLed2, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 60, -1, -1));

        jPanelLed1.setBackground(java.awt.Color.gray);
        jPanelLed1.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jPanelLed1Layout = new javax.swing.GroupLayout(jPanelLed1);
        jPanelLed1.setLayout(jPanelLed1Layout);
        jPanelLed1Layout.setHorizontalGroup(
            jPanelLed1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelLed1Layout.setVerticalGroup(
            jPanelLed1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelLed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setText("OFF(0)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 40, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setText("ON(1)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 125, 30, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setText("ON(1)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 135, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setText("ON(1)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 135, 30, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setText("OFF(0)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 40, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setText("OFF(0)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 40, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel7.setText("DipSwitchs");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 70, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("MODULE 01");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel9.setText("Connection - USB");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 110, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel10.setText("Action Modes");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 90, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel11.setText("Control Mode");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 100, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel12.setText("PushButtons");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 70, -1));

        jLabel13.setText("7");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 46, 10, -1));

        jLabel14.setText("1");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 46, 10, -1));

        jLabel15.setText("2");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 46, 10, -1));

        jLabel16.setText("3");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 46, 10, -1));

        jLabel17.setText("4");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 46, 10, -1));

        jLabel18.setText("5");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 46, 10, -1));

        jLabel19.setText("6");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 46, 10, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 10, 90));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 390, 10));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 390, 10));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 10, 180));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 105, 10));

        binMode.setSelected(true);
        binMode.setText("Bin2Dec");
        binMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binModeActionPerformed(evt);
            }
        });
        getContentPane().add(binMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 120, 30));

        gatesMode.setText("Gates");
        gatesMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gatesModeActionPerformed(evt);
            }
        });
        getContentPane().add(gatesMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 110, 40));

        jPanelConnection.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanelConnectionLayout = new javax.swing.GroupLayout(jPanelConnection);
        jPanelConnection.setLayout(jPanelConnectionLayout);
        jPanelConnectionLayout.setHorizontalGroup(
            jPanelConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelConnectionLayout.setVerticalGroup(
            jPanelConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelConnection, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 345, 50, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jCheckBoxSoftware.setSelected(true);
        jCheckBoxSoftware.setText("By Software");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jCheckBoxSoftware, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jCheckBoxSoftware)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 130, 22));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jCheckBoxHardware.setText("By Hardware");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jCheckBoxHardware, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jCheckBoxHardware))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 130, 22));

        jButtonConnect.setText("Connect");
        getContentPane().add(jButtonConnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 120, 25));

        jButtonDisconnect.setText("Disconnect");
        getContentPane().add(jButtonDisconnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 120, 25));

        jToggleButtonInput1.setBackground(java.awt.Color.white);
        jToggleButtonInput1.setForeground(java.awt.Color.white);
        jToggleButtonInput1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pb1.jpg"))); // NOI18N
        getContentPane().add(jToggleButtonInput1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 58, 45));

        jToggleButtonInput2.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButtonInput2.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButtonInput2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pb2.jpg"))); // NOI18N
        getContentPane().add(jToggleButtonInput2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 58, 45));

        jMenuFile.setMnemonic('F');
        jMenuFile.setText("File");

        jMenuItemRestart.setMnemonic('R');
        jMenuItemRestart.setText("Restart");
        jMenuFile.add(jMenuItemRestart);
        jMenuFile.add(jSeparator7);

        jMenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);
        jMenuFile.getAccessibleContext().setAccessibleDescription("");

        jMenuEdit.setText("Edit");

        jMenuContolMode.setText("Control Mode");

        jRadioButtonMenuItemSoftware.setSelected(true);
        jRadioButtonMenuItemSoftware.setText("Controled by Software");
        jMenuContolMode.add(jRadioButtonMenuItemSoftware);

        jRadioButtonMenuItemHardware.setText("Controled by Hardware");
        jMenuContolMode.add(jRadioButtonMenuItemHardware);

        jMenuEdit.add(jMenuContolMode);
        jMenuEdit.add(jSeparator10);

        jMenuConnection.setText("Connection");

        jRadioButtonMenuItemConnected.setText("Connected");
        jMenuConnection.add(jRadioButtonMenuItemConnected);

        jRadioButtonMenuItemDisconnected.setSelected(true);
        jRadioButtonMenuItemDisconnected.setText("Disconnected");
        jMenuConnection.add(jRadioButtonMenuItemDisconnected);

        jMenuEdit.add(jMenuConnection);

        jMenuBar1.add(jMenuEdit);

        jMenuHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png"))); // NOI18N
        jMenuHelp.setText("Help");

        jMenuItemUpdate.setText("Update");
        jMenuHelp.add(jMenuItemUpdate);
        jMenuHelp.add(jSeparator9);

        jMenuItemAbout.setText("About");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemAbout);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
    
    private void binModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binModeActionPerformed
        jComboBoxGatesMenu.setEnabled(false);
        jToggleButtonInput1.setEnabled(false);
        jToggleButtonInput2.setEnabled(false);
        if (!binMode.isSelected() && mode == false) {
            binMode.setSelected(true);
        }
        gatesMode.setSelected(false);
        jSliderDSW1.setEnabled(true);
        jSliderDSW2.setEnabled(true);
        jSliderDSW3.setEnabled(true);
    }//GEN-LAST:event_binModeActionPerformed

    private void gatesModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gatesModeActionPerformed
        jComboBoxGatesMenu.setEnabled(true);
        jToggleButtonInput1.setEnabled(true);
        jToggleButtonInput2.setEnabled(true);
        if (!gatesMode.isSelected() && mode == true) {
            gatesMode.setSelected(true);
            mode = false;
        }
        binMode.setSelected(false);
        jSliderDSW1.setEnabled(false);
        jSliderDSW2.setEnabled(false);
        jSliderDSW3.setEnabled(false);
    }//GEN-LAST:event_gatesModeActionPerformed

    public void refreshLeds() {
        jPanelLed1.setBackground(Color.GRAY);
        jPanelLed2.setBackground(Color.GRAY);
        jPanelLed3.setBackground(Color.GRAY);
        jPanelLed4.setBackground(Color.GRAY);
        jPanelLed5.setBackground(Color.GRAY);
        jPanelLed6.setBackground(Color.GRAY);
        jPanelLed7.setBackground(Color.GRAY);
        decimalValue = jSliderDSW1.getValue() + jSliderDSW2.getValue() * 2 + jSliderDSW3.getValue() * 4;
        switch (decimalValue) {
            case 1:
                jPanelLed1.setBackground(Color.GREEN);
                break;
            case 2:
                jPanelLed1.setBackground(Color.GREEN);
                jPanelLed2.setBackground(Color.GREEN);
                break;
            case 3:
                jPanelLed1.setBackground(Color.GREEN);
                jPanelLed2.setBackground(Color.GREEN);
                jPanelLed3.setBackground(Color.GREEN);
                break;
            case 4:
                jPanelLed1.setBackground(Color.GREEN);
                jPanelLed2.setBackground(Color.GREEN);
                jPanelLed3.setBackground(Color.GREEN);
                jPanelLed4.setBackground(Color.GREEN);
                break;
            case 5:
                jPanelLed1.setBackground(Color.GREEN);
                jPanelLed2.setBackground(Color.GREEN);
                jPanelLed3.setBackground(Color.GREEN);
                jPanelLed4.setBackground(Color.GREEN);
                jPanelLed5.setBackground(Color.GREEN);
                break;
            case 6:
                jPanelLed1.setBackground(Color.GREEN);
                jPanelLed2.setBackground(Color.GREEN);
                jPanelLed3.setBackground(Color.GREEN);
                jPanelLed4.setBackground(Color.GREEN);
                jPanelLed5.setBackground(Color.GREEN);
                jPanelLed6.setBackground(Color.GREEN);
                break;
            case 7:
                jPanelLed1.setBackground(Color.GREEN);
                jPanelLed2.setBackground(Color.GREEN);
                jPanelLed3.setBackground(Color.GREEN);
                jPanelLed4.setBackground(Color.GREEN);
                jPanelLed5.setBackground(Color.GREEN);
                jPanelLed6.setBackground(Color.GREEN);
                jPanelLed7.setBackground(Color.GREEN);
                break;
            default:
                break;
        }
    }

    private void jSliderDSW3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderDSW3MouseClicked
        refreshLeds();
    }//GEN-LAST:event_jSliderDSW3MouseClicked

    private void jSliderDSW2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderDSW2MouseClicked
        refreshLeds();
    }//GEN-LAST:event_jSliderDSW2MouseClicked

    private void jSliderDSW1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderDSW1MouseClicked
        refreshLeds();
    }//GEN-LAST:event_jSliderDSW1MouseClicked

    private void jSliderDSW3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderDSW3MouseDragged
        refreshLeds();
    }//GEN-LAST:event_jSliderDSW3MouseDragged

    private void jSliderDSW3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderDSW3MouseMoved
        refreshLeds();
    }//GEN-LAST:event_jSliderDSW3MouseMoved

    private void jSliderDSW3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderDSW3MouseEntered
        refreshLeds();
    }//GEN-LAST:event_jSliderDSW3MouseEntered

    private void jSliderDSW3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderDSW3MousePressed
        refreshLeds();
    }//GEN-LAST:event_jSliderDSW3MousePressed

    private void jSliderDSW2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderDSW2MouseDragged
        refreshLeds();
    }//GEN-LAST:event_jSliderDSW2MouseDragged

    private void jSliderDSW2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderDSW2MouseEntered
        refreshLeds();
    }//GEN-LAST:event_jSliderDSW2MouseEntered

    private void jSliderDSW2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderDSW2MouseMoved
        refreshLeds();
    }//GEN-LAST:event_jSliderDSW2MouseMoved

    private void jSliderDSW2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderDSW2MousePressed
        refreshLeds();
    }//GEN-LAST:event_jSliderDSW2MousePressed

    private void jSliderDSW2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderDSW2MouseReleased
        refreshLeds();
    }//GEN-LAST:event_jSliderDSW2MouseReleased

    private void jSliderDSW1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderDSW1MouseDragged
        refreshLeds();
    }//GEN-LAST:event_jSliderDSW1MouseDragged

    private void jSliderDSW1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderDSW1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jSliderDSW1MouseEntered

    private void jSliderDSW1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderDSW1MouseMoved
        refreshLeds();
    }//GEN-LAST:event_jSliderDSW1MouseMoved

    private void jSliderDSW1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderDSW1MousePressed
        refreshLeds();
    }//GEN-LAST:event_jSliderDSW1MousePressed

    private void jSliderDSW1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderDSW1MouseReleased
        refreshLeds();
    }//GEN-LAST:event_jSliderDSW1MouseReleased

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        System.exit(EXIT_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
      
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton binMode;
    private javax.swing.JRadioButton gatesMode;
    private javax.swing.JButton jButtonConnect;
    private javax.swing.JButton jButtonDisconnect;
    private javax.swing.JCheckBox jCheckBoxHardware;
    private javax.swing.JCheckBox jCheckBoxSoftware;
    private javax.swing.JComboBox jComboBoxGatesMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConnection;
    private javax.swing.JMenu jMenuContolMode;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemRestart;
    private javax.swing.JMenuItem jMenuItemUpdate;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelConnection;
    private javax.swing.JPanel jPanelLed1;
    private javax.swing.JPanel jPanelLed2;
    private javax.swing.JPanel jPanelLed3;
    private javax.swing.JPanel jPanelLed4;
    private javax.swing.JPanel jPanelLed5;
    private javax.swing.JPanel jPanelLed6;
    private javax.swing.JPanel jPanelLed7;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemConnected;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemDisconnected;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemHardware;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemSoftware;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JSlider jSliderDSW1;
    private javax.swing.JSlider jSliderDSW2;
    private javax.swing.JSlider jSliderDSW3;
    private javax.swing.JToggleButton jToggleButtonInput1;
    private javax.swing.JToggleButton jToggleButtonInput2;
    // End of variables declaration//GEN-END:variables
}
