/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Eduardo
 */
public class tela extends javax.swing.JFrame {

    private int decimalValue, gate;
    private boolean mode;

    /**
     * Creates new form tela
     */
    public tela() {
        initComponents();
        mode = true; // False = GatesMode | True = BinMode
        binMode.setSelected(true);
        gatesMode.setSelected(false);
        gatesMenu.setEnabled(false);
        //jButtonSync.setIcon(new ImageIcon(("sync.jpg")));
        decimalValue = gate = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        gatesMenu = new javax.swing.JComboBox();
        dsw3 = new javax.swing.JSlider();
        dsw2 = new javax.swing.JSlider();
        dsw1 = new javax.swing.JSlider();
        led7 = new javax.swing.JPanel();
        led6 = new javax.swing.JPanel();
        led5 = new javax.swing.JPanel();
        led4 = new javax.swing.JPanel();
        led3 = new javax.swing.JPanel();
        led2 = new javax.swing.JPanel();
        led1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        binMode = new javax.swing.JRadioButton();
        gatesMode = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jButtonSync = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISDEM");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(415, 380));
        setMinimumSize(new java.awt.Dimension(415, 380));
        setPreferredSize(new java.awt.Dimension(415, 380));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gatesMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NOT (NÃO)", "AND (E)", "OR (OU)", "NOR", "NAND" }));
        getContentPane().add(gatesMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 130, 30));

        dsw3.setMaximum(1);
        dsw3.setOrientation(javax.swing.JSlider.VERTICAL);
        dsw3.setValue(0);
        dsw3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dsw3MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                dsw3MouseMoved(evt);
            }
        });
        dsw3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dsw3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dsw3MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dsw3MousePressed(evt);
            }
        });
        getContentPane().add(dsw3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 30, 65));

        dsw2.setMaximum(1);
        dsw2.setOrientation(javax.swing.JSlider.VERTICAL);
        dsw2.setToolTipText("");
        dsw2.setValue(0);
        dsw2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dsw2MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                dsw2MouseMoved(evt);
            }
        });
        dsw2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dsw2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dsw2MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dsw2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dsw2MouseReleased(evt);
            }
        });
        getContentPane().add(dsw2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 30, 65));

        dsw1.setMaximum(1);
        dsw1.setOrientation(javax.swing.JSlider.VERTICAL);
        dsw1.setValue(0);
        dsw1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dsw1MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                dsw1MouseMoved(evt);
            }
        });
        dsw1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dsw1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dsw1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dsw1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dsw1MouseReleased(evt);
            }
        });
        getContentPane().add(dsw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 40, 65));

        led7.setBackground(java.awt.Color.gray);
        led7.setToolTipText("");
        led7.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout led7Layout = new javax.swing.GroupLayout(led7);
        led7.setLayout(led7Layout);
        led7Layout.setHorizontalGroup(
            led7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        led7Layout.setVerticalGroup(
            led7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(led7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        led6.setBackground(java.awt.Color.gray);
        led6.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout led6Layout = new javax.swing.GroupLayout(led6);
        led6.setLayout(led6Layout);
        led6Layout.setHorizontalGroup(
            led6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        led6Layout.setVerticalGroup(
            led6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(led6, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 60, -1, -1));

        led5.setBackground(java.awt.Color.gray);
        led5.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout led5Layout = new javax.swing.GroupLayout(led5);
        led5.setLayout(led5Layout);
        led5Layout.setHorizontalGroup(
            led5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        led5Layout.setVerticalGroup(
            led5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(led5, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 60, -1, 30));

        led4.setBackground(java.awt.Color.gray);
        led4.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout led4Layout = new javax.swing.GroupLayout(led4);
        led4.setLayout(led4Layout);
        led4Layout.setHorizontalGroup(
            led4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        led4Layout.setVerticalGroup(
            led4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(led4, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 60, -1, -1));

        led3.setBackground(java.awt.Color.gray);
        led3.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout led3Layout = new javax.swing.GroupLayout(led3);
        led3.setLayout(led3Layout);
        led3Layout.setHorizontalGroup(
            led3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        led3Layout.setVerticalGroup(
            led3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(led3, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 60, -1, -1));

        led2.setBackground(java.awt.Color.gray);
        led2.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout led2Layout = new javax.swing.GroupLayout(led2);
        led2.setLayout(led2Layout);
        led2Layout.setHorizontalGroup(
            led2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        led2Layout.setVerticalGroup(
            led2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(led2, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 60, -1, -1));

        led1.setBackground(java.awt.Color.gray);
        led1.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout led1Layout = new javax.swing.GroupLayout(led1);
        led1.setLayout(led1Layout);
        led1Layout.setHorizontalGroup(
            led1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        led1Layout.setVerticalGroup(
            led1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(led1, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setText("OFF");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 215, 30, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setText("ON");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 125, 20, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setText("ON");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 135, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setText("ON");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 135, 20, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setText("OFF");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 215, 30, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setText("OFF");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 215, 30, 20));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 10, 75));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 390, 10));

        binMode.setSelected(true);
        binMode.setText("Bin2Dec");
        binMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binModeActionPerformed(evt);
            }
        });
        getContentPane().add(binMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        gatesMode.setText("Gates");
        gatesMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gatesModeActionPerformed(evt);
            }
        });
        getContentPane().add(gatesMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 120, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel7.setText("DipSwitchs");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 90, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("MODULE 01");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 15, -1, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 390, 10));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel9.setText("Synchronization");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 255, 110, -1));

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 284, 50, 50));

        jToggleButton1.setText("Connect");
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 282, 90, -1));

        jToggleButton2.setText("Disconnect");
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 90, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel10.setText("Modes");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 60, -1));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 20, 130));

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel11.setText("Connection");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 255, 70, -1));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 35, 105, 10));

        jButtonSync.setText("Sync");
        getContentPane().add(jButtonSync, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 165, 55));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void binModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binModeActionPerformed
        mode = true;
        if (!binMode.isSelected()) {
            binMode.setSelected(true);
        }
        gatesMode.setSelected(false);
        gatesMenu.setEnabled(false);
    }//GEN-LAST:event_binModeActionPerformed

    private void gatesModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gatesModeActionPerformed
        gatesMenu.setEnabled(true);
        mode = false;
        if (!gatesMode.isSelected()) {
            gatesMode.setSelected(true);
        }
        binMode.setSelected(false);
    }//GEN-LAST:event_gatesModeActionPerformed

    public void refreshLeds() {
        led1.setBackground(Color.GRAY);
        led2.setBackground(Color.GRAY);
        led3.setBackground(Color.GRAY);
        led4.setBackground(Color.GRAY);
        led5.setBackground(Color.GRAY);
        led6.setBackground(Color.GRAY);
        led7.setBackground(Color.GRAY);
        decimalValue = dsw1.getValue() + dsw2.getValue() * 2 + dsw3.getValue() * 4;
        switch (decimalValue) {
            case 1:
                led1.setBackground(Color.GREEN);
                break;
            case 2:
                led1.setBackground(Color.GREEN);
                led2.setBackground(Color.GREEN);
                break;
            case 3:
                led1.setBackground(Color.GREEN);
                led2.setBackground(Color.GREEN);
                led3.setBackground(Color.GREEN);
                break;
            case 4:
                led1.setBackground(Color.GREEN);
                led2.setBackground(Color.GREEN);
                led3.setBackground(Color.GREEN);
                led4.setBackground(Color.GREEN);
                break;
            case 5:
                led1.setBackground(Color.GREEN);
                led2.setBackground(Color.GREEN);
                led3.setBackground(Color.GREEN);
                led4.setBackground(Color.GREEN);
                led5.setBackground(Color.GREEN);
                break;
            case 6:
                led1.setBackground(Color.GREEN);
                led2.setBackground(Color.GREEN);
                led3.setBackground(Color.GREEN);
                led4.setBackground(Color.GREEN);
                led5.setBackground(Color.GREEN);
                led6.setBackground(Color.GREEN);
                break;
            case 7:
                led1.setBackground(Color.GREEN);
                led2.setBackground(Color.GREEN);
                led3.setBackground(Color.GREEN);
                led4.setBackground(Color.GREEN);
                led5.setBackground(Color.GREEN);
                led6.setBackground(Color.GREEN);
                led7.setBackground(Color.GREEN);
                break;
            default:
                break;
        }
    }

    private void dsw3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsw3MouseClicked
        refreshLeds();
    }//GEN-LAST:event_dsw3MouseClicked

    private void dsw2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsw2MouseClicked
        refreshLeds();
    }//GEN-LAST:event_dsw2MouseClicked

    private void dsw1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsw1MouseClicked
        refreshLeds();
    }//GEN-LAST:event_dsw1MouseClicked

    private void dsw3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsw3MouseDragged
        refreshLeds();
    }//GEN-LAST:event_dsw3MouseDragged

    private void dsw3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsw3MouseMoved
        refreshLeds();
    }//GEN-LAST:event_dsw3MouseMoved

    private void dsw3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsw3MouseEntered
        refreshLeds();
    }//GEN-LAST:event_dsw3MouseEntered

    private void dsw3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsw3MousePressed
        refreshLeds();
    }//GEN-LAST:event_dsw3MousePressed

    private void dsw2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsw2MouseDragged
        refreshLeds();
    }//GEN-LAST:event_dsw2MouseDragged

    private void dsw2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsw2MouseEntered
        refreshLeds();
    }//GEN-LAST:event_dsw2MouseEntered

    private void dsw2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsw2MouseMoved
        refreshLeds();
    }//GEN-LAST:event_dsw2MouseMoved

    private void dsw2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsw2MousePressed
        refreshLeds();
    }//GEN-LAST:event_dsw2MousePressed

    private void dsw2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsw2MouseReleased
        refreshLeds();
    }//GEN-LAST:event_dsw2MouseReleased

    private void dsw1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsw1MouseDragged
        refreshLeds();
    }//GEN-LAST:event_dsw1MouseDragged

    private void dsw1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsw1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dsw1MouseEntered

    private void dsw1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsw1MouseMoved
        refreshLeds();
    }//GEN-LAST:event_dsw1MouseMoved

    private void dsw1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsw1MousePressed
        refreshLeds();
    }//GEN-LAST:event_dsw1MousePressed

    private void dsw1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsw1MouseReleased
        refreshLeds();
    }//GEN-LAST:event_dsw1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton binMode;
    private javax.swing.JSlider dsw1;
    private javax.swing.JSlider dsw2;
    private javax.swing.JSlider dsw3;
    private javax.swing.JComboBox gatesMenu;
    private javax.swing.JRadioButton gatesMode;
    private javax.swing.JButton jButtonSync;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JPanel led1;
    private javax.swing.JPanel led2;
    private javax.swing.JPanel led3;
    private javax.swing.JPanel led4;
    private javax.swing.JPanel led5;
    private javax.swing.JPanel led6;
    private javax.swing.JPanel led7;
    // End of variables declaration//GEN-END:variables
}
