/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.game;

import gnu.io.SerialPortEvent;
import gnu.io.SerialPortEventListener;
import java.awt.EventQueue;
import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Eduardo
 */
public class MainFrame extends javax.swing.JFrame implements SerialPortEventListener {

    /**
     * Constants of the system
     */
    private static final DateFormat FORMATO = new SimpleDateFormat("mm:ss"); // Format the date type

    /**
     * Control variables of the system
     */
    private static SerialCOM arduinoCommunication;   // Serial communication with ArduinoUNO board
    private int minutes, seconds, remainingTimeSeconds;     // Variables to control counter
    private String counterText;         // Strores counter in String format
    private boolean isPaused;    // Controls counter 

    /**
     * Creates new form MainInterface
     */
    public MainFrame() {
        /**
         * Initialize variables and components of the system.
         */
        initComponents();
        initVariables();

        /**
         * Starts thread to update counter.
         */
        Thread clockThread = new Thread(new ClockRunnable(), "Clock Thread");
        clockThread.setDaemon(true);
        clockThread.start();
    }

    /**
     * Method that starts importants variables.
     */
    private void initVariables() {
        arduinoCommunication = new SerialCOM();
        arduinoCommunication.initialize();
        minutes = seconds = remainingTimeSeconds = 0;
        counterText = null;
        isPaused = true;
        getCounterString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldScorePlayer1 = new javax.swing.JTextField();
        jButtonStart = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabelResultPlayer1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jToggleButtonPause = new javax.swing.JToggleButton();
        jButtonClear = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldScorePlayer2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabelResultPlayer3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSpinnerMinutes = new javax.swing.JSpinner();
        jSpinnerSeconds = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldRemainigTime = new javax.swing.JTextField();
        jButtonSetCounter = new javax.swing.JButton();
        jTextFieldDecimalRandom2 = new javax.swing.JTextField();
        jTextFieldDecimalRandom1 = new javax.swing.JTextField();
        jTextFieldDecimalPlayer1 = new javax.swing.JTextField();
        jTextFieldDecimalRandom3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISDEM GAME - Convert In Time Game");
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 1330, 13));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel1.setText("JOGADOR 01");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel2.setText("JOGADOR 02");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 400, -1, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 14, 340));

        jLabel3.setText("PONTUAÇÃO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, -1, -1));

        jTextFieldScorePlayer1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jTextFieldScorePlayer1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jTextFieldScorePlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, 170, 60));

        jButtonStart.setText("INICIAR");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 230, 210, 110));

        jLabel5.setText("RESULTADO FINAL ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 600, -1, -1));

        jLabelResultPlayer1.setBackground(new java.awt.Color(204, 255, 255));
        jLabelResultPlayer1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabelResultPlayer1.setName(""); // NOI18N
        getContentPane().add(jLabelResultPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 620, 220, 60));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setText("TEMPO RESTANTE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 310, 60));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("AÇÕES");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 70, -1, -1));

        jToggleButtonPause.setText("PAUSAR / CONTINUAR");
        jToggleButtonPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPauseActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonPause, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 120, 100, 90));

        jButtonClear.setText("ZERAR");
        getContentPane().add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 120, 100, 90));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 20, 310));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 50, 20, 320));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setText("DURAÇÃO DA PARTIDA");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 220, 30));

        jLabel10.setText("VALOR INFORMADO (JOGADOR)");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, -1, -1));

        jLabel11.setText("VALOR DECIMAL (ALEATÓRIO)");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, -1));

        jLabel12.setText("PONTUAÇÃO ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 590, -1, -1));

        jTextFieldScorePlayer2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        getContentPane().add(jTextFieldScorePlayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 620, 170, 60));

        jLabel13.setText("RESULTADO FINAL ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 600, -1, -1));

        jLabelResultPlayer3.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        getContentPane().add(jLabelResultPlayer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 620, 220, 60));

        jLabel14.setText("VALOR INFORMADO (JOGADOR)");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 460, -1, -1));

        jLabel15.setText("VALOR DECIMAL (ALEATÓRIO)");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, -1, -1));

        jSpinnerMinutes.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jSpinnerMinutes.setToolTipText("");
        jSpinnerMinutes.setName(""); // NOI18N
        getContentPane().add(jSpinnerMinutes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 80, 80));

        jSpinnerSeconds.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        getContentPane().add(jSpinnerSeconds, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 80, 80));

        jLabel4.setText("Minutos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel6.setText("Segundos");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel16.setText(":");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 170, 20, -1));

        jTextFieldRemainigTime.setEditable(false);
        jTextFieldRemainigTime.setFont(new java.awt.Font("Tahoma", 0, 150)); // NOI18N
        jTextFieldRemainigTime.setText("00:00");
        getContentPane().add(jTextFieldRemainigTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, 270));

        jButtonSetCounter.setText("DEFINIR");
        jButtonSetCounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetCounterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSetCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 200, 80));
        getContentPane().add(jTextFieldDecimalRandom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 490, 80, 70));
        getContentPane().add(jTextFieldDecimalRandom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 80, 70));
        getContentPane().add(jTextFieldDecimalPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 80, 70));
        getContentPane().add(jTextFieldDecimalRandom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 490, 80, 70));

        getAccessibleContext().setAccessibleName("SISDEM GAME - Convert In Time");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method to define match time duration
     *
     * @param evt
     */
    private void jButtonSetCounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetCounterActionPerformed
        getMatchDuration();
        try {
            setCouterString(FORMATO.parse(Integer.toString(minutes) + ":" + Integer.toString(seconds)));
        } catch (ParseException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("The game duration has been set.");
    }//GEN-LAST:event_jButtonSetCounterActionPerformed

    /**
     * Method that stops counter
     *
     * @param evt
     */
    private void jToggleButtonPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPauseActionPerformed
        if (jToggleButtonPause.isSelected()) {
            isPaused = true;
            System.out.println("System OFF");
        } else {
            isPaused = false;
            System.out.println("System ON");
        }
    }//GEN-LAST:event_jToggleButtonPauseActionPerformed

    /**
     * Method that starts system's processing
     *
     * @param evt
     */
    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        isPaused = false;
        jButtonSetCounter.setEnabled(false);
        jButtonClear.setEnabled(false);
        gameAction();
    }//GEN-LAST:event_jButtonStartActionPerformed

    /**
     *
     */
    private void getCounterString() {
        // Get text from counterText
        counterText = jTextFieldRemainigTime.getText();
    }

    /**
     * Método para atualizar a hora no formulário. Não é thread-safe, portanto,
     * se o utilizado fora da thread da AWT, deve-se utilizar um dos comandos da
     * EventQueue (invokeLater ou invokeAndWait).
     *
     * @param date
     */
    public void setCouterString(Date date) {
        jTextFieldRemainigTime.setText(FORMATO.format(date));
    }

    /**
     *
     */
    private void getMatchDuration() {
        minutes = Integer.parseInt(jSpinnerMinutes.getValue().toString());
        seconds = Integer.parseInt(jSpinnerSeconds.getValue().toString());
    }

    /**
     *
     */
    private void calcRemaningTime() {
        // Get reamaning total time
        getCounterString();
        // Get reamaning minutes
        int remainingMinutes = Integer.parseInt(counterText.substring(0, 2));
        // Get reamaning seconds
        int remainingSeconds = Integer.parseInt(counterText.substring(3, 5));
        // Calc total reamaning seconds
        remainingTimeSeconds = (remainingMinutes * 60) + remainingSeconds;
        // Decrement 1 second
        if (remainingTimeSeconds > 0) {
            remainingTimeSeconds--;
        }
        // Calc reamaning minutes
        remainingMinutes = remainingTimeSeconds / 60;
        // Calc reamaning seconds
        remainingSeconds = remainingTimeSeconds % 60;
        // Making reamaning time in String
        counterText = String.valueOf(remainingMinutes) + ":" + String.valueOf(remainingSeconds);
        try {
            // Set reamaning time in text field
            setCouterString(FORMATO.parse(counterText));
        } catch (ParseException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     *
     */
    private void gameAction() {
        System.out.println("The game has been staterd...");
    }

    /**
     *
     * @param spe
     */
    @Override
    public synchronized void serialEvent(SerialPortEvent spe) {
        arduinoCommunication.serialEvent(spe);
    }

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Thread listenSerial = new Thread() {
            @Override
            public void run() {
                /**
                 * The following line will keep this app alive for 1000 seconds,
                 * waiting for events to occur and responding to them (printing
                 * incoming messages to console).
                 */
                //try {
                //Thread.sleep(1000000);
                //Thread.sleep(10000);
                //} catch (InterruptedException ie) {
                //}
            }
        };
        listenSerial.start();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    /**
     * Runnable que contém o código que atuará na nossa thread. Basicamente, ele
     * chama o método setCouterString de segundo em segundo, passando a data
     * atual.
     */
    private class ClockRunnable implements Runnable {

        @Override
        public void run() {
            try {
                while (true) {
                    // Aqui chamamos o setCouterString através da EventQueue da AWT.  
                    // Conforme dito, isso garante Thread safety para o Swing.  
                    EventQueue.invokeLater(() -> {
                        if (!isPaused) {
                            calcRemaningTime();
                        } else {
                            //System.out.println("System is paused.");
                        }
                    });
                    // Fazemos nossa thread dormir por um segundo, liberando o  
                    // processador para outras threads processarem.  
                    Thread.sleep(1000);
                }
            } catch (InterruptedException e) {
                //
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonSetCounter;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelResultPlayer1;
    private javax.swing.JLabel jLabelResultPlayer3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSpinner jSpinnerMinutes;
    private javax.swing.JSpinner jSpinnerSeconds;
    private javax.swing.JTextField jTextFieldDecimalPlayer1;
    private javax.swing.JTextField jTextFieldDecimalRandom1;
    private javax.swing.JTextField jTextFieldDecimalRandom2;
    private javax.swing.JTextField jTextFieldDecimalRandom3;
    private javax.swing.JTextField jTextFieldRemainigTime;
    private javax.swing.JTextField jTextFieldScorePlayer1;
    private javax.swing.JTextField jTextFieldScorePlayer2;
    private javax.swing.JToggleButton jToggleButtonPause;
    // End of variables declaration//GEN-END:variables
}
