/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.game;

import java.awt.EventQueue;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javafx.scene.chart.PieChart;

/**
 *
 * @author Eduardo
 */
public class MainInterface extends javax.swing.JFrame {

    // Formatador da hora  
    private static final DateFormat FORMATO = new SimpleDateFormat("mm:ss");
    private int minutes, seconds;

    /**
     * Creates new form MainInterface
     */
    public MainInterface() {
        initComponents();

        getMatchDuration();

        Thread clockThread = new Thread(new ClockRunnable(), "Clock thread");
        clockThread.setDaemon(true);
        clockThread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPointingPlayer1 = new javax.swing.JTextField();
        jButtonIniciar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabelResultPlayer1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jToggleButtonPause = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jButtonDefineMatchDuration = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldPointingPlayer2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabelResultPlayer3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSpinnerMinutes = new javax.swing.JSpinner();
        jSpinnerSeconds = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldTempoRestante = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISDEM GAME - Convert In Time Game");
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 1330, 13));

        jLabel1.setText("JOGADOR 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        jLabel2.setText("JOGADOR 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 400, -1, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, 14, 340));

        jLabel3.setText("PONTUAÇÃO: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 600, -1, -1));

        jTextFieldPointingPlayer1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jTextFieldPointingPlayer1.setText("0,0 pontos");
        jTextFieldPointingPlayer1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jTextFieldPointingPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 170, 60));

        jButtonIniciar.setText("INICIAR");
        getContentPane().add(jButtonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 230, 210, 115));

        jLabel5.setText("RESULTADO FINAL: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 600, -1, -1));

        jLabelResultPlayer1.setBackground(new java.awt.Color(204, 255, 255));
        jLabelResultPlayer1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabelResultPlayer1.setName(""); // NOI18N
        getContentPane().add(jLabelResultPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 630, 200, 60));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setText("TEMPO RESTANTE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 310, 60));

        jLabel8.setText("AÇÕES");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 70, -1, -1));

        jToggleButtonPause.setText("PAUSAR");
        getContentPane().add(jToggleButtonPause, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 120, 100, 90));

        jButton1.setText("ZERAR");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 120, 100, 90));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 20, 330));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 50, 20, 320));

        jLabel9.setText("DURAÇÃO DA PARTIDA");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 120, 30));

        jButtonDefineMatchDuration.setText("DEFINIR");
        getContentPane().add(jButtonDefineMatchDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 200, 60));

        jLabel10.setText("VALOR INFORMADO");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, -1, -1));

        jLabel11.setText("VALOR DECIMAL GERADO");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, -1));

        jLabel12.setText("PONTUAÇÃO: ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 600, -1, -1));

        jTextFieldPointingPlayer2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jTextFieldPointingPlayer2.setText("0,0 pontos");
        getContentPane().add(jTextFieldPointingPlayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 630, 170, 60));

        jLabel13.setText("RESULTADO FINAL: ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 600, -1, -1));

        jLabelResultPlayer3.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        getContentPane().add(jLabelResultPlayer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 630, 220, 60));

        jLabel14.setText("VALOR INFORMADO");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 460, -1, -1));

        jLabel15.setText("VALOR DECIMAL GERADO");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 460, -1, -1));

        jSpinnerMinutes.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jSpinnerMinutes.setToolTipText("");
        jSpinnerMinutes.setName(""); // NOI18N
        getContentPane().add(jSpinnerMinutes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 80, 80));

        jSpinnerSeconds.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        getContentPane().add(jSpinnerSeconds, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 80, 80));

        jLabel4.setText("Minutos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel6.setText("Segundos");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        jLabel16.setText(":");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 10, -1));

        jTextFieldTempoRestante.setEditable(false);
        jTextFieldTempoRestante.setFont(new java.awt.Font("Tahoma", 0, 150)); // NOI18N
        jTextFieldTempoRestante.setText("00:00");
        getContentPane().add(jTextFieldTempoRestante, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, 270));

        getAccessibleContext().setAccessibleName("SISDEM GAME - Convert In Time");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método para atualizar a hora no formulário. Não é thread-safe, portanto,
     * se o utilizado fora da thread da AWT, deve-se utilizar um dos comandos da
     * EventQueue (invokeLater ou invokeAndWait).
     *
     * @param date
     */
    public void setHora(Date date) {
        jTextFieldTempoRestante.setText(FORMATO.format(date));
    }

    private void getMatchDuration() {
        minutes = Integer.parseInt(jSpinnerMinutes.getValue().toString());
        seconds = Integer.parseInt(jSpinnerSeconds.getValue().toString());
    }

    /**
     * Runnable que contém o código que atuará na nossa thread. Basicamente, ele
     * chama o método setHora de segundo em segundo, passando a data atual.
     */
    private class ClockRunnable implements Runnable {

        public void run() {
            try {
                while (true) {
                    // Aqui chamamos o setHora através da EventQueue da AWT.  
                    // Conforme dito, isso garante Thread safety para o Swing.  
                    EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            // Só podemos chamar setHora diretamente dessa  
                            // forma, pois esse Runnable é uma InnerClass não  
                            // estática.  
                            setHora(new Date());
                        }
                    });
                    // Fazemos nossa thread dormir por um segundo, liberando o  
                    // processador para outras threads processarem.  
                    Thread.sleep(1000);
                }
            } catch (InterruptedException e) {
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDefineMatchDuration;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelResultPlayer1;
    private javax.swing.JLabel jLabelResultPlayer3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSpinner jSpinnerMinutes;
    private javax.swing.JSpinner jSpinnerSeconds;
    private javax.swing.JTextField jTextFieldPointingPlayer1;
    private javax.swing.JTextField jTextFieldPointingPlayer2;
    private javax.swing.JTextField jTextFieldTempoRestante;
    private javax.swing.JToggleButton jToggleButtonPause;
    // End of variables declaration//GEN-END:variables
}
